apiVersion: apps/v1
# *object kind
kind: Deployment
metadata:
  # deployment uniquely identify
  name: nginx-deployment
  # annotations for custom metadate
# object spec
spec:
  # *object resource label
  selector:
    matchLabels:
      app: nginx
  # pod template
  template:
    metadata:
      # pod label
      labels:
        app: nginx
    # pod spec
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1
        ports:
        - containerPort: 80

